package com.example.tripmate.ui.theme

import androidx.compose.ui.graphics.Color

// Hex values from DESIGN.md

val OnTertiaryContainer = Color(0xFF00312B)
val SurfaceDim = Color(0xFFD8DADC)
val SurfaceContainerHigh = Color(0xFFE6E8EA)
val TertiaryFixed = Color(0xFF62FAE3)
val InverseSurface = Color(0xFF2D3133)
val OnTertiary = Color(0xFFFFFFFF)
val OnPrimaryContainer = Color(0xFF5A0C00)
val OnBackground = Color(0xFF191C1E)
val ErrorColor = Color(0xFFBA1A1A)
val OnPrimaryFixedVariant = Color(0xFF8C1900)
val SurfaceBright = Color(0xFFF7F9FB)
val OnPrimary = Color(0xFFFFFFFF)
val SurfaceColor = Color(0xFFF7F9FB)
val OnPrimaryFixed = Color(0xFF3D0600)
val ErrorContainer = Color(0xFFFFDAD6)
val OnSecondaryFixed = Color(0xFF131B2E)
val TertiaryFixedDim = Color(0xFF3CDDC7)
val OnSurfaceVariant = Color(0xFF5B403A)
val InverseOnSurface = Color(0xFFEFF1F3)
val SecondaryFixed = Color(0xFFDAE2FD)
val InversePrimary = Color(0xFFFFB4A3)
val OnSecondaryContainer = Color(0xFF5C647A)
val SecondaryFixedDim = Color(0xFFBEC6E0)
val OnSecondaryFixedVariant = Color(0xFF3F465C)
val TertiaryColor = Color(0xFF006B5F)
val SurfaceContainerLow = Color(0xFFF2F4F6)
val OnSecondary = Color(0xFFFFFFFF)
val OnTertiaryFixedVariant = Color(0xFF005047)
val OnError = Color(0xFFFFFFFF)
val OutlineVariant = Color(0xFFE3BEB6)
val SecondaryContainer = Color(0xFFDAE2FD)
val BackgroundColor = Color(0xFFF7F9FB)
val SurfaceTint = Color(0xFFB52603)
val OnErrorContainer = Color(0xFF93000A)
val OnTertiaryFixed = Color(0xFF00201C)
val PrimaryContainer = Color(0xFFFF5A36)
val SurfaceContainer = Color(0xFFECEEF0)
val SurfaceVariant = Color(0xFFE0E3E5)
val PrimaryFixed = Color(0xFFFFDAD2)
val PrimaryFixedDim = Color(0xFFFFB4A3)
val Outline = Color(0xFF8F7069)
val SecondaryColor = Color(0xFF565E74)
val TertiaryContainer = Color(0xFF00A493)
val OnSurface = Color(0xFF191C1E)
val SurfaceContainerHighest = Color(0xFFE0E3E5)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val PrimaryColor = Color(0xFFB52603)